name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-guangzhou.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/aliyun0135914335/ngnix:latest docker://registry.cn-hangzhou.aliyuncs.com/xu247/ngnix:latest
         skopeo copy docker://docker.io/aliyun0135914335/httpd:latest docker://registry.cn-hangzhou.aliyuncs.com/xu247/httpd:latest
         skopeo copy docker://docker.io/aliyun0135914335/bind:latest docker://registry.cn-hangzhou.aliyuncs.com/xu247/bind:latest
         skopeo copy docker://docker.io/aliyun0135914335/vsftpd:latest docker://registry.cn-hangzhou.aliyuncs.com/xu247/vsftpd:latest
         
         
         
